README.md

Revert "Эта картиночка лучше вродь."

---

Resources/Prototypes/_Reserve/ERT/ERT.yml

**Медиа**
**Проверки**
:cl:
- fix: Исправлено что-то там что-то там
- fix: Исправлена `важная штука` которая ломала `другую важную штуку`
- remove: Убрана `незначительная штука` которая мешала работе `важной штуки`
- add: Крутая штука!
- tweak: Изменены параметры `обычной штуки` чтобы игроки моги меньше ей пользоваться

Custom-ERT

---

Content.Server/Administration/Commands/AdminWhoCommand.cs

админвху теперь для всех
**Проверки**
:cl: nodjak
- tweak: админвху теперь доступен всем игрокам

Adminwho for all

---

Content.Shared/CombatMode/CombatModeComponent.cs
Content.Shared/CombatMode/SharedCombatModeSystem.cs

ещё [порт с корвакс нехт](https://github.com/space-syndicate/space-station-14-next/pull/133)!!!
**Проверки**

360 фонарики

---

Resources/Maps/Reserve/sillyisland.yml

Ай-ай-ай, станнеры реверса попали в руки СБ!!!
+ нормальная камера в бриге
**Проверки**

Silly hotfix

---

Resources/Maps/Reserve/sillyisland.yml

Фикс эвака на силли

---

Resources/Locale/ru-RU/_DV/voice/speech-emotes.ftl
Resources/Prototypes/_DV/Voice/speech_emotes.yml

Микро локализация эмоций вульп
**Проверки**

Локализация вулькапинов

---

Content.Server/Corvax/PeacefulRoundEnd/PeacefulRoundEndSystem.cs
Content.Server/_Reserve/PeacefulRoundEnd/PeacefulRoundEndSystem.cs
Content.Shared/_Reserve/CCCVars/CCCVars.cs

Выдача пацифизма и годмода после раунда. Летающие клоуны в космосе теперь реальны.
[Порт с корвуха](https://github.com/space-syndicate/space-station-14/pull/761)
**Проверки**

Пацифизм и годмод после раунда

---

Resources/Prototypes/GameRules/roundstart.yml

Мелкие правки шансов режимов.
:cl: 9ush_ka
- fix: Теперь для режима "Ядерные Оперативники" требуется 30+ игроков.

Мелкие правки шансов режимов

---

Resources/Maps/Reserve/cluster.yml
Resources/Maps/Reserve/saltern.yml

очередное обновление салтерна и клулустера

another maps upd

---

Tools/publish_multi_request.py

ноджак лох

---

Tools/publish_github_artifact.py

**Медиа**
**Проверки**
:cl:
- fix: Исправлено что-то там что-то там
- fix: Исправлена `важная штука` которая ломала `другую важную штуку`
- remove: Убрана `незначительная штука` которая мешала работе `важной штуки`
- add: Крутая штука!
- tweak: Изменены параметры `обычной штуки` чтобы игроки моги меньше ей пользоваться

ноджак лох 2

---

Resources/Maps/Reserve/saltern.yml
Resources/Prototypes/_Reserve/Maps/saltern.yml

Fixes saltern

---

Resources/Maps/Reserve/saltern.yml

Обновил салтерн(опять)

---

Resources/Prototypes/Entities/Objects/Materials/ore.yml

Update ore.yml (#1811)

---

Resources/Locale/ru-RU/_Goobstation/servercurrency/server_currency.ftl
Resources/Prototypes/_Goobstation/ServerCurrency/token_listings.yml

Переделал систему токенов под нас

---

Content.Server/Nuke/NukeComponent.cs

increase 30>60

---

Resources/Locale/ru-RU/_Goobstation/Changeling/abilities/changeling.ftl
Resources/Locale/ru-RU/_Goobstation/Changeling/store/changeling-catalog.ftl

В основном переведены способности, которые сейчас на английском.
**Медиа**
**Проверки**

Перевёл немного генокрадов

---

Content.Client/Interactable/Components/InteractionOutlineComponent.cs
Resources/Textures/Shaders/outline.swsl

Обводка теперь учитывает цвета соседних пикселей, а новый экземпляр шейдера не создается каждый раз при наведении, спс чатгпт
**Медиа**
https://github.com/user-attachments/assets/d17b7599-1168-4168-8535-499dc47328de
слайм прикол
**Проверки**
:cl: nodjak
- tweak: Теперь обводка при наведении учитывает цвета спрайта

Уродская зеленая обводка стала еще хуже

---

Resources/Prototypes/_Goobstation/Recipes/Reactions/toxins.yml

Изменил триклор, точнее его рецепт, убрав из него хлор и добавив ихор. Зачем это нужно? Чтобы нельзя было быстро сделать данный яд и не травить всех.
**Медиа**
**Проверки**
:cl: ThxMqninq
- tweak: Изменен рецепт триклора во избежании всяких злодейств

Триклор и рецепт

---

Resources/Prototypes/_Goobstation/GameRules/Dynamic/midround.yml
Resources/Prototypes/_Goobstation/GameRules/Dynamic/roundstart.yml
Resources/Prototypes/_Goobstation/GameRules/midround.yml
Resources/Prototypes/_Goobstation/GameRules/roundstart.yml

хз в том ли была проблема или нет))
**Медиа**
**Проверки**
:cl: csqrb
- fix: Пофикшено(?) что революция не всегда была только по согласию.

Фикс ревы(?)

---

Content.Server/Chat/Systems/ChatSystem.cs
Content.Server/Radio/EntitySystems/RadioSystem.cs

Если отправляешь в IC "/", сообщение не отправится.
Бывает, спешишь отправить дохуя важное сообщение своими дрожащими ручками, "Я ДОЛБАЕБ ААААААААААА", однако, промахиваешься на enter, и в чат извергается "Я ДОЛБАЕБ ААААААААААА /////". 
P.s. Впервые сру пулреквест, говорите, если хуйню сделал. 
**Медиа**
**Проверки**
:cl: kutos
- tweak: Никаких "/" в IC чат.

Анти кривые ручки систем

---

.github/workflows/publish.yml

Always setup NET core
JUST DO IT.

Publish fix always setup NET core

---

Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml

Добавил педалям в сумку всякий нужный стафф, чтобы не спавнить каждый раз.
Очень нужно! Без этого никуда!
yml
**Changelog**
:cl: Svarshik
Admin:
- add: Добавлено веселье администраторам в сумку.

Admin satchel new stuff added

---

Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Security/undetermined_item.yml

Удален сикуси у всех, кроме шефа. Он останется на шаттле дедов, но, думаю, это вообще не проблема.
Просьба администрации сервера. Баланс. Сикуси на пг-шашем щите немного не то что надо.
yml 
:cl:
- add: Шеф-повару вернули CQC!
- remove: Отняли CQC у ОСЩ и предателей с ядерными оперативниками.

No cqc (balance police)

---

Content.Shared/Zombies/ZombieComponent.cs

Увеличена регенерация зомби. Теперь зомби регенерируют все виды урона. 
См. трекер: https://discord.com/channels/1291325264227471410/1360618700373495829
Changed values in ZombieComponent.cs
Циферки:
Скорость зомби 70% -> 85%
Регенерация в секунду:
Blunt,-0.4 -> -1
Slash -0.2 -> -1
Piercing -0.2 -> -1
Heat 0 -> 0.5
Регенерация за 1 укус:
Blunt -2 -> -10
Slash -2 -> -10
Piercing -2 -> -10
Heat 0 -> -10
Stamina 0 -> -25
**Changelog**
:cl: Svarshik
- tweak: Усилены зомби!

Zombie buff

---

Resources/Prototypes/Entities/Mobs/Player/human.yml
Resources/Prototypes/Entities/Objects/Tools/decoys.yml
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/_Goobstation/Datasets/Names/military.yml
Resources/Prototypes/_Goobstation/Entities/Mobs/Player/admeme.yml
Resources/Prototypes/_Goobstation/GameRules/Admeme/token.yml
Resources/Prototypes/_Goobstation/GameRules/roundstart.yml
Resources/Prototypes/_Reserve/DS/DS.yml
Resources/Prototypes/_Reserve/ERT/ERT.yml
Resources/Prototypes/_Reserve/Entities/Spawners/CBURNUnit.yml
Resources/Prototypes/_Reserve/Entities/Spawners/CBURNUnitLeader.yml
Resources/Prototypes/_Reserve/Entities/Spawners/ERTEngineer.yml
Resources/Prototypes/_Reserve/Entities/Spawners/ERTJanitor.yml
Resources/Prototypes/_Reserve/Entities/Spawners/ERTLeader.yml
Resources/Prototypes/_Reserve/Entities/Spawners/ERTMedical.yml
Resources/Prototypes/_Reserve/Entities/Spawners/ERTSecurity.yml

Актуализация датасетов.
Исправление бага с отображением неправильных имен у нюк и типов с ЦК.
changed referred datasets from legacy to localized ones
no cl

Datasets fix

---

Content.Client/HealthAnalyzer/UI/HealthAnalyzerWindow.xaml
Content.Server/Medical/Components/HealthAnalyzerComponent.cs
Content.Server/Medical/HealthAnalyzerSystem.cs

Порт https://github.com/DeltaV-Station/Delta-v/pull/3521 к нам.
QoL фича.

[Port] Health Analyzer Reactivation 

---

Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
Content.Shared/Radio/RadioChannelPrototype.cs
Resources/Prototypes/radio_channels.yml

Добавлен специальный компонент, который прячет ключ шифрования синдиката, если он вставлен не в гарнитуру, в которой синдикатовский канал не является каналом по умолчанию.
Стелс антаги не сущетсвуют, но стелс-нюка ещё что-то может. Энивей полезно.
потом может
:cl:
- tweak: Ключ шифрования синдиката больше не видно при осмотре гарнитуры.

Stealth syndie key

---

Content.Goobstation.Server/Bingle/BinglePitSystem.cs

Бингле? Бингле!
https://github.com/WWhiteDreamProject/wwdpublic/pull/437
Теперь если в яму бинглов закинуть любой контейнер - очки будут прибавляться за каждую сущность, содержащуюся в этом контейнере.
Теперь если в яме бинглов окажется стак чего-либо, то количество прибавленных очков будет равно количеству предметов в стаке.
**Changelog**
:cl:
- tweak: Теперь если в яму бинглов закинуть любой контейнер - очки будут прибавляться за каждую сущность, содержащуюся в этом контейнере.
- tweak: Теперь если в яме бинглов окажется стак чего-либо, то количество прибавленных очков будет равно количеству предметов в стаке.

[Port] THE PIT MUST GROW

---

Content.Server/_White/Commands/PoshelnahuiCommand.cs

Порт https://github.com/WWhiteDreamProject/wwdpublic/pull/438 для педалей
1984

[Port] Poshelnahui admin

---

Resources/Prototypes/Entities/Objects/Tools/welders.yml

Твики с экспериментальным сварочником. Теперь более уникальный предмет, нежели тупо бесконечная сварка.
Значительно изменяет экспериментальный сварочный аппарат. Вместо практически обычного сварочного аппарата с практически неограниченным количеством топлива, теперь это сверхбыстрый сварочный аппарат с замедленной самозаправкой и гораздо меньшим запасом топлива. 
Ещё изменён усовершенствованный промышленный сварочный аппарат, чтобы сделать его по-прежнему стоящим предметом.
ynl
:cl:
- tweak: Изменены промышленный и экспериментальный сварочные аппараты.

[Port] Experimental welder rework

---

Content.Server/_White/Administration/Commands/InvisibilityCommand.cs
Content.Server/_White/Administration/Commands/VisibilityCommand.cs
Content.Shared/Eye/VisibilityFlags.cs
Resources/Locale/en-US/_white/administration/commands/invisibility.ftl
Resources/Locale/ru-RU/_white/administration/commands/invisibility.ftl
Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml

Порт пр с ввдп https://github.com/WWhiteDreamProject/wwdpublic/pull/429
Невидимая педаль чтобы госты не доебывали

[Port] Invisibility 

---

Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Specific/rehydrateable.yml

Удаляет сигма кубы толчков, ещё какую-то сигма херню с толчками из аплинка.
Ну нахуя это делали. Господи блять.

Remove sigma shit

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml

Убрана коробка с шприцами пакса из локера ГВ.
Пакс - вещество, используемое психологами для лечений всяких ментальных болезней, но из-за нынешнего контингента сервера пакс используется совсем не для этого. Да и не стоит давать подобные лекарства именно в локер ГВ, который просто руководит отделом и иногда занимается работой, ему это ни к чему

No pax for CMO

---

Resources/Prototypes/_White/GameRules/midround.yml

Ивент только для админов чтобы спавнить мидраунд нюку (обычный рул выдергивает игроков из раунда)
Порт https://github.com/WWhiteDreamProject/wwdpublic/pull/428

Midround nukies

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml

Добавил гаечный ключ в шкафчик СМО.
Баунти https://discordapp.com/channels/1291325264227471410/1368872530860970025
**Changelog**

Wrench for CMO

---

Content.Server/Objectives/Components/PickRandomPersonComponent.cs
Content.Server/Objectives/Systems/KillPersonConditionSystem.cs
Resources/Prototypes/Objectives/traitor.yml

Порт https://github.com/DeltaV-Station/Delta-v/pull/2799.
Зачастую агентам падали цельки на опера/абдуктора/мага/ертишника/уриста с админ аренки. С фиксом в качестве цели могут быть выданы только те роли, которые можно изначально выбрать для присоединения в лобби.
**Changelog**
:cl:
- fix: Теперь корректно выдаются цели на убийство. Больше никаких целей "убей абдуктора"

Correct kill objectives

---

Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs
Content.Server/StationEvents/RampingStationEventSchedulerSystem.cs
Resources/Prototypes/GameRules/roundstart.yml

Порт https://github.com/DeltaV-Station/Delta-v/pull/3277
Технические детали там же. Изменяет появление событий в режиме выживания, теперь можно контролировать частоту появление ивентов с помощью списка векторов.

[Port] Reworked event progression

---

Content.Server/Administration/ServerApi.cs

Forgor that i removed it bruh
Относится к https://github.com/echotry-ss14/Reserve-Station/pull/207

bwoink back in serverapi.cs

---

Content.Goobstation.Shared/Bible/BibleComponent.cs
Content.Goobstation.Shared/Factory/AutomationSystem.cs
Resources/Prototypes/Entities/Clothing/Head/helmets.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Misc/filters.yml
Resources/Prototypes/_Goobstation/Entities/Objects/Tools/upgrade_kits.yml
Resources/Prototypes/_Goobstation/Entities/Structures/Machines/robotic_arm.yml
Resources/Prototypes/_Goobstation/Guidebook/chaplain.yml

Post upstream fixes

---

Tools/publish_github_artifact.py
Tools/publish_multi_request.py

Publish tweak

---

.github/workflows/changelog.yml
Resources/Changelog/ReserveChangelog.yml
Resources/Locale/ru-RU/changelog/changelog-window.ftl
Tools/changelog/changelog.js

Сделал автоматический апдейт чейнджолга, адаптировав губовский.

Automatic changelog update yay

---

Content.Goobstation.Server/Blob/BlobFactorySystem.cs
Content.Goobstation.Server/Blob/Components/BlobFactoryComponent.cs
Content.Goobstation.Server/Blob/NPC/BlobPod/BlobPodSystem.cs
Content.Goobstation.Server/Blob/ZombieBlobSystem.cs
Content.Goobstation.Shared/Blob/Components/BlobPodComponent.cs

Фабрики блоба теперь будут производить больше спор, чтобы достичь предела (3), когда их споры погибают
Фабрики стают бесполезными после того, как погибли все споры.
Порт https://github.com/funky-station/funky-station/pull/565
**Changelog**
:cl: 
- tweak: Фабрики блоба теперь делают новые споры даже после того как старые погибли.

[Port] Better blob facrory

---

Content.Server/Administration/ServerApi.cs
Resources/Locale/ru-RU/discord/round-notifications.ftl

Название говорит само за себя.
сачтук просил
no cl no fun

small tweaks dont care about em

---

Content.Server/Construction/ConstructionSystem.Initial.cs
Content.Server/Revenant/EntitySystems/RevenantSystem.cs
Content.Server/_Impstation/Revenant/EntitySystems/RevenantStasisSystem.cs
Content.Shared/Eye/VisibilityFlags.cs
Content.Shared/Revenant/Components/RevenantComponent.cs
Content.Shared/StatusEffect/StatusEffectsComponent.cs
Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
Resources/Prototypes/Entities/Objects/Materials/ore.yml
Resources/Prototypes/status_effects.yml

Исправил стазис ревенанта (см. #138 ), теперь работает корректно
Починил видимость монумента космо-культа. (см. #220 )
bugs
:cl: Svarshik
- fix: Исправлена видимость космического монумента
- fix: Исправлен Стазис ревенанта

Revenant fixes + monument visibiluty
